version: 2
registries:
  python-index-pypi-python-org-simple:
    type: python-index
    url: https://pypi.python.org/simple/

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  registries:
  - python-index-pypi-python-org-simple
